### PR TITLE
Make more indentation rules based on line of first sibling

### PR DESCRIPTION
**Pull request by danielmatz**
This is a continuation of some previous work to make indentation rules more contextual. Indentation styles tend to differ depending on whether the first child of the parent is on the same line as the parent or on its own line.

This commit extends this logic to tuple expressions, vector and matrix expressions, type parameter lists, and curly brace expressions.

This commit also corrects the behavior of assignment expressions. Those were incorrectly aligning to the identifier being assigned to when the julia-ts-align-assignment-expressions-to-first-sibling variable was set to t.

Lastly, this commit generalizes the matcher function used to implement these features and expands its documentation.

### CODE REVIEW

**Comment by ronisbr** [comment]
Hi @danielmatz !

I did some modifications to you code. For some reason, the assignment was not working here. The problem is how the grammar treats expressions in an assignment. For example:

```julia
a = 1 + 3 +
4 + 5
```

is parsed as:

```
(assignment (identifier) (operator)
 (binary_expression
  (binary_expression
   (binary_expression (integer_literal) (operator) (integer_literal))
   (operator) (integer_literal))
  (operator) (integer_literal)))
```

Notice that the parent of the node `4` is a `binary_expression` instead of `assignment`. Hence, to properly align everything, we need to search for an ancestor node that is of type `assingnment`.

Can you please test the code in `main` and check if everything still works?

**Comment by ronisbr** [comment]
If everything is ok, I will tag the new version. The modifications you did were amazing! The indentation is much more consistent now :)

**Comment by danielmatz** [comment]
Great! Glad to help!

The changes you made look good to me. Thanks for catching my typos and standardizing my doc strings!

**Comment by ronisbr** [comment]
Perfect! Thank you very much for the contribution :)

**Pull request merged**
