### PR TITLE
Add break and continue to keywords

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Comment by ronisbr** [comment]
Thanks!

**Comment by ronisbr** [comment]
Hi @chriselrod!

I have to revert. This commit breaks the font-locking. `break` and `continue` are not exported as keywords. We need to highlight `(break_statement)` and `(continue_statement)`. I push a commit to do this.

**Comment by ronisbr** [comment]
Done!

**Comment by chriselrod** [comment]
Ah, sorry, my bad!
I'll test locally before making a PR next time.

**Comment by ronisbr** [comment]
No problem at all!! Thanks to inform me that those keywords were not being highlighted :D

**Pull request merged**
